login/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('auth/', include('social_django.urls', namespace='social')),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='login'),
    path('', views.ngetes),
]

testimoni/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.testimoni_page),
    path('addtesti/', views.add_testimoni),
]

tugas_1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

"""
Isi url halaman di bagian folder tugas1/urls.py yg disini dia bakal include ke urls.py yg di app
!!~ Jadi ga perlu rubah2 urls.py yg disini lagi ~!!
"""
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tugas1.urls')),
    path('user/', include('login.urls')),
    path('testimoni/', include('testimoni.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

testimoni/models.py
from django.db import models

# Create your models here.
from django.utils import timezone


class testimoniUser(models.Model):
    comment = models.CharField(max_length=300)
    time = models.DateTimeField(default=timezone.now)

testimoni/forms.py
from django import forms

class testimoni(forms.Form):
    comment = forms.CharField(widget=forms.TextInput({'class': 'form-control'}), label="", max_length=300)

testimoni/views.py
import datetime
from django.shortcuts import render
from testimoni.forms import testimoni
from testimoni.models import testimoniUser


def testimoni_page(request):
    form = testimoni()
    date = datetime.datetime.now()
    response = {'form': form, 'get_comment': testimoniUser.objects.all().order_by('-time'), 'datetime': date}
    return render(request, 'testimoni.html', response)


response = {}
def add_testimoni(request):
    if request.method == "POST":
        print("masuk nih mau post")
        form = testimoni(request.POST or None)
        if form.is_valid():
            response['comment'] = request.POST['comment']
            testi = testimoniUser(comment=response['comment'])
            testi.save()
            return render(request, 'testimoni.html', response)
        else:
            print("not valid")
    else:
        print("ke else terakhir")

testimoni/templates/testimoni.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">
    <title>Testimoni</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}"/>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light sticky-top bg-light" role="navigation">
    <a class="navbar-brand" href="">
        <a href="/"><img src="https://image.ibb.co/fyHFT0/skuy.png" width="120" height="40"
                         class="d-inline-block align-top"
                         alt="home"></a>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto" style="top: 50%;">
            <li class="nav-item">
                <a class="nav-link" href="/">Beranda</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/berita">Berita</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/donasi">Donasi</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/testimoni">Testimoni</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="/user/logout/">Keluar</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="/user/login/">Masuk</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>
<div class="col-12 login box bg-light" style="margin-top: 5%;">
    <center>
        {% if not user.is_authenticated %}

            {% for testi in get_comment %}

                <ul>
                    <li>
                        <h4>{{ testi.comment }}</h4>
                        Waktu : {{ testi.time }} <br>
                    </li>
                </ul>

            {% endfor %}

        {% else %}

            <form id="form" method="POST">
                <h3>Testimoni :</h3>
                {% csrf_token %}
                {{ form }}
                <br>
                <button id="tombol" type="submit" class="btn btn-primary btn-lg active">Kirim</button>
            </form>
            </center><br><br>
            <div id="komen" style="text-align:left;">
                {% for testi in get_comment %}
                    <div>
                        <ul>
                            <li>
                                <h4>{{ testi.comment }}</h4>
                                Waktu : {{ testi.time }}<br>
                            </li>
                        </ul>
                    </div>
                {% endfor %}
            </div>

        {% endif %}
</div>

</body>

<script>
    $(document).ready(function () {
        $('#tombol').click(function () {
            var komen = {
                csrfmiddlewaretoken: '{{ csrf_token }}',
                comment: $('#id_comment').val()
            };

            $.ajax({
                type: "POST",
                url: "/testimoni/addtesti/",
                data: komen,
                success: function (data) {
                    $('#komen').load(/testimoni/ + " #komen");
                    {#$('.ajaxNih').hide();#}
                    document.getElementById("form").reset();
                },
                error: function (data) {
                    alert("ERROR !@#$%^&()");
                }
            })
        })
    })
</script>

</html>